### PR TITLE
erlang 20.3.8

### PR DESCRIPTION
**Pull request by getong**
Besides, erlang 21.0 is just released now. Will it be supported?

### CODE REVIEW

**Comment by dincho** [comment]
@lucafavatella What's your opinion on bumping the erlang/OTP version of our build environment ?

**Comment by lucafavatella** [comment]
@dincho I definitely want to bump the OTP version, though I would prefer that be (1) planned as part of an iteration and (2) mentioned/agreed in the core development team. BTW the macOS package OTP version would need to be bumped at the same time.

Based http://erlang.org/download/otp_src_20.3.readme there shall not be breaking changes with 20.2 though:
* Some compilation warnings in epoch or its deps may have been turned to errors in OTP 20.3. If any, these shall be fixed first;
* I see some SSL build changes in OTP 20.3 - not sure if this impacts epoch, shall be checked;
* OTP Mnesia DB patches in epoch - if still present and applicable - shall be checked;
* I would like to see 20.3.* actually used as part of the workflow of at least one Developer/Contributor before moving the whole infrastructure across.

**Comment by dincho** [comment]
> I would like to see 20.3.* actually used as part of the workflow of at least one Developer/Contributor before moving the whole infrastructure across.

Are you volunteer ? :)

**Comment by dincho** [comment]
Tracking as https://www.pivotaltracker.com/story/show/158490458

**Comment by dincho** [comment]
> OTP Mnesia DB patches in epoch - if still present and applicable - shall be checked;

As far as I see we have OTP patches for `20.1` only - https://github.com/aeternity/epoch/tree/master/otp_patches

**Comment by dincho** [comment]
> Some compilation warnings in epoch or its deps may have been turned to errors in OTP 20.3. If any, these shall be fixed first;
> I see some SSL build changes in OTP 20.3 - not sure if this impacts epoch, shall be checked;
> I would like to see 20.3.* actually used as part of the workflow of at least one Developer/Contributor before moving the whole infrastructure across.

@hanssv can confirm it's working as expected

**Comment by dincho** [comment]
> (2) mentioned/agreed in the core development team.

I posted notification on internal channels and got no objections.

**Pull request merged**
